import s from "./TermsContent.module.css";
import HeaderList from "../../HeaderList/HeaderList";

const TermsContent = () => {
    return(
        <section className={s.terms}>
            <div className={s.container}>
                <HeaderList/>
                <h3 className={s.title}>Terms of Use</h3>
                <p className={s.text}>Aliquam porta nisl dolor, molestie pellentesque elit molestie in. Morbi metus neque, elementum ullamcorper hendrerit eget, tincidunt et nisi. Sed magna nunc, consequat vel aliquam vitae, porta ac mi. Integer commodo sapien lacus, nec interdum nisi vehicula aliquam. Aliquam enim lorem, laoreet ut egestas quis, rutrum sed lectus. Duis et purus in dolor bibendum egestas vel vitae urna. Vestibulum dictum semper laoreet. Nulla augue tellus, aliquam mollis quam eget, maximus iaculis sem. Praesent semper ex tortor, in rhoncus arcu sollicitudin ut. Donec magna lorem, efficitur quis fringilla sed, imperdiet sed risus. Nam accumsan, elit sit amet pretium commodo, turpis augue molestie eros, quis maximus diam ex eget libero. Aliquam erat volutpat. Integer interdum arcu nisi. Cras venenatis lorem in molestie pulvinar. Donec a tortor et magna suscipit consectetur. </p>
                <p className={s.text}>Sed mi lacus, vehicula id ex nec, vulputate pretium urna. Aenean accumsan facilisis ornare. Aenean porttitor augue at erat aliquam, quis mattis nunc egestas. Morbi malesuada lorem tortor, sed aliquam ante laoreet et. Nulla facilisi. Nulla nisl velit, blandit vel sagittis et, venenatis et leo. Mauris nec metus pretium, hendrerit lectus in, iaculis diam. Fusce massa odio, lacinia id leo at, eleifend egestas nibh. Etiam placerat magna sit amet scelerisque pulvinar. Quisque tempor ex nulla. Nullam non aliquam mauris, nec semper velit. Duis aliquam fermentum sem quis fermentum. Nunc at nunc vitae sem tempor vestibulum. Sed commodo a tortor placerat lacinia. Mauris placerat tempor nibh, lobortis imperdiet mauris egestas nec. Quisque tincidunt ex non lacus finibus euismod. Praesent congue turpis a pulvinar varius. Etiam tempor sapien in viverra tincidunt. Donec vel lacus ultricies, rhoncus odio sit amet, gravida magna. Curabitur posuere lacus id diam porta pulvinar. Maecenas lacus mauris, laoreet quis hendrerit eget, lacinia et elit. Donec venenatis condimentum quam, at feugiat massa mollis ullamcorper. Aliquam accumsan mi vitae leo tempor venenatis. Nulla facilisi. Vivamus vestibulum, turpis eu varius venenatis, odio felis tempor nulla, ut placerat quam nisl in tellus. Cras rutrum fermentum tempor. Aliquam volutpat imperdiet sapien, ac volutpat lectus rhoncus in. </p>
                <p className={s.text}>Cras tortor nulla, ornare ac urna a, volutpat pellentesque tellus. Fusce volutpat sapien porttitor, sodales arcu quis, malesuada augue. Pellentesque eu fringilla enim, a scelerisque ligula. Sed vel mollis diam, id ornare mauris. Quisque non hendrerit nisl, vel finibus tellus. Nulla condimentum metus mattis, aliquet magna sit amet, dictum nisl. Integer vehicula fermentum lobortis. Integer vel placerat sem. Donec viverra vulputate ligula, ut imperdiet felis condimentum eu. Duis at sollicitudin odio, ac finibus nibh. Etiam eu libero molestie, iaculis nisi vel, varius nibh. Donec pharetra augue quis nulla efficitur, at ultricies risus lacinia. Sed fermentum arcu a viverra elementum. Duis viverra elit ac ligula eleifend egestas. Cras mollis ut libero sed euismod. Sed at rhoncus ipsum, et malesuada nulla. Fusce sit amet mauris sit amet leo gravida pulvinar. Etiam sapien magna, tempor ut augue sit amet, pellentesque convallis tellus. Suspendisse potenti. Vivamus quis aliquam urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla varius neque et sem convallis, eu sollicitudin velit luctus. Aenean mollis diam commodo massa rhoncus porta. In dignissim imperdiet varius. In ut massa ex. Quisque tincidunt ultricies nisi, sit amet lobortis velit imperdiet vel. Suspendisse sed convallis mauris, non aliquam lorem. Duis augue justo, dictum ut lacinia eget, dignissim vitae urna. Ut bibendum elit vel viverra volutpat. Aliquam tempus nisl tempor nunc consequat laoreet. Integer ut mattis nisi. Proin tincidunt, risus sit amet eleifend rhoncus, lectus orci dapibus nibh, sit amet vestibulum est justo ut ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut sed eleifend urna. Curabitur eleifend cursus nulla, in egestas eros rhoncus quis. Quisque placerat facilisis lacinia. </p>
            </div>
        </section>
    )
}

export default  TermsContent